### ISSUE TITLE
github connection requires too many permissions

### ISSUE THREAD

**Issue by barthuijgen** [cicadahq/cicada#43]
The permission screen to sign in with Cicada

<img width="496" alt="cicada-permission" src="https://user-images.githubusercontent.com/45095973/233841412-d874337f-9b39-4e74-8c3f-c255369658fd.png">

Can access basically everything on my account!

As comaprison, here is another service that needs access to code: Deno deploy

<img width="517" alt="deno-deploy-permissions" src="https://user-images.githubusercontent.com/45095973/233841452-757fe7f9-f153-4004-832b-150fd45f13d7.png">

And similar services like cloudflare pages, etc will allow you to select what repositories to give access to.

Thanks for the early waitlist invite, but I can not test Cicada with these permissions.

**Comment by grant0417** [comment]
I don't think we actually need all of these permissions and is its a bug to request all of them at the start, will confirm tomorrow.

**Comment by grant0417** [comment]
@mschrage thoughts on this?

**Comment by mschrage** [comment]
I think we can downscope permissions to read-only for repos. (We need to be able to list them prior to the user adding the Github app to their org/personal account)

**Comment by grant0417** [comment]
Hey @barthuijgen, we did some work and reduced the needed permissions to just your user and orgs, no more repo access.
