### ISSUE TITLE
Cannot view results in dashboard except for first pipeline run

### ISSUE THREAD

**Issue by GJZwiers** [cicadahq/cicada#50]
I have been trying out Cicada in one of my projects, but if I go to the dashboard I can only view the logs for the very first pipeline that I ran. I can only view the results for later pipeline runs in the links that are posted by the Cicada Bot in my PRs, but not on the dashboard.

![image](https://user-images.githubusercontent.com/34610306/234518479-a48b9f18-81d0-47b7-8b34-26f97fead6ee.png)

In the browser console (Firefox) there are a few errors:

```
Object { input: {…}, result: TRPCClientError, elapsedMs: 384, context: {} }
​
context: Object {  }
​
elapsedMs: 384
​
input: Object { namespace: undefined, repo: undefined }
​
result: TRPCClientError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "namespace"
    ],
    "message": "Required"
  }
]
​
<prototype>: Object { … }

Firefox can’t establish a connection to the server at wss://cicada-ws.fly.dev/. 4 [_app-5ea6b5860d5394e9.js:5:66099](https://cicada.build/_next/static/chunks/pages/_app-5ea6b5860d5394e9.js)
Firefox can’t establish a connection to the server at wss://cicada-ws.fly.dev/. [_app-5ea6b5860d5394e9.js:5:66099](https://cicada.build/_next/static/chunks/pages/_app-5ea6b5860d5394e9.js)
Firefox can’t establish a connection to the server at wss://cicada-ws.fly.dev/.
```

This is my pipeline file:

```ts
import { Job, Pipeline } from "https://deno.land/x/cicada@v0.1.46/mod.ts";

const job = new Job({
  name: "My First Job",
  image: "ubuntu:22.04",
  steps: [
    {
      name: "Run bash",
      run: "echo hello from bash!",
    },
    {
      name: "Run deno/typescript",
      run: () => {
        console.log("Hello from deno typescript");
        console.log("I can read the local file system");
        console.log("e.g. here are all the directories in my project");
        console.log(Array.from(Deno.readDirSync("/app")));
        console.log("Or I can see my environment variables");
        console.log(Deno.env.toObject());
      },
    },
  ],
});

export default new Pipeline([job], {
  on: {
    pullRequest: ["main"],
    push: ["main"],
  },
});

```

**Comment by grant0417** [comment]
@mschrage @superbryntendo any idea what is happening here?

**Comment by superbryntendo** [comment]
Hmmm. Appears to not be common to all orgs. @GJZwiers is there any chance the name of the org or the repo changed recently?

Clearly it's not getting all the data it needs but it could be that it's an earlier request given that the other run is loading (we have several requests that fail per page load before the router has loaded)

Many of these errors would be resolved by SSR.

**Comment by GJZwiers** [comment]
@superbryntendo I did change the repo name something like 2-3 months ago.

**Comment by mschrage** [comment]
It looks like other runs are getting "skipped" because they don't match the triggers you've set on the pipeline.

<img width="681" alt="Screenshot 2023-04-27 at 11 32 18 AM" src="https://user-images.githubusercontent.com/3155109/234959103-c1200c6a-58b4-4013-8ecd-c9b0f14b66e2.png">

**Comment by mschrage** [comment]
Hey @GJZwiers! Other runs are getting skipped because they don't match your trigger conditions. Currently, the pipeline will only run when on the "main" branch.

**Comment by GJZwiers** [comment]
Thanks @mschrage , it's working now. Closing this.
