### ISSUE TITLE
[bug] specified file not found

### ISSUE THREAD

**Issue by jhechtf** [cicadahq/cicada#52]
I've installed the cicada CLI, and generated a file named `Astro.ts`, but this is the error i get every time.

Cicada has been authorized in github.

```
cicada run Astro

 ◥◣ ▲ ◢◤  Cicada is in alpha, it may not work as expected
  ◸ ▽ ◹   Please report any issues here: https://github.com/cicadahq/cicada

✅ Downloaded deno v1.32.5
[error] specified file not found in archive
```

**Comment by mschrage** [comment]
Can you share the Astro.ts file?

**Comment by jhechtf** [comment]
It is the default one generated for node when I ran the init script

**Comment by mschrage** [comment]
Can you run `cicada doctor` and share the output here?

**Comment by grant0417** [comment]
@jhechtf can you install manually Deno, it seems that our auto install didnt work.

What OS are you on?

**Comment by jhechtf** [comment]
Deno is already installed on my computer, but it is a different version
than the one being downloaded.

This was run on a windows 10 machine.

**Comment by grant0417** [comment]
Currently it just requires Deno >=1.32, not specifically 1.32.5. But yeah updating it should resolve this issue, also looking into actually fixing it.

**Comment by grant0417** [comment]
Hopefully this commit will resolve it: https://github.com/cicadahq/cicada/commit/a818c41452ffac49ad2ae7af9faabf5154742954

Ill create a new release soon!

**Comment by grant0417** [comment]
I believe this is also now resolved in https://github.com/cicadahq/cicada/tree/v0.1.48 so I am going to close the issue
